name = "zipp"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "zipp_database"
database_id = "8a89a445-7646-414d-9aad-4e0d973d0f7b"
migrations_dir = "./drizzle"

[[durable_objects.bindings]]
name = "LOCATION_TRACKER"
class_name = "LocationTracker"
script_name = "zipp-location-tracker"

# [[migrations]]
# tag = "v1"
# new_classes = ["LocationTracker"]

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "zipp-storage"
